Repository sparta-nuTTTy/nuttty-delivery, pull requests merged in 2024-09, with the labels that each got.

#19 [#4] 허브 엔티티 생성 및 연관관계 매핑
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/HubApplication.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/domain/model/AuditEntity.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/domain/model/Hub.java
Labels: enhancement

#26 [#13] HubRoutes 엔티티 생성 및 연관관계 매핑
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/domain/model/HubRoutes.java
Labels: enhancement

#27 [#7] 업체 엔티티 생성 및 연관관계 매핑
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/CompanyApplication.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/domain/model/AuditEntity.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/domain/model/Company.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/domain/model/CompanyType.java
Labels: enhancement

#28 [#10] Product 엔티티 생성 및 연관관계 매핑
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/domain/model/Product.java
Labels: enhancement

#32 [#29] Feat: "회원 가입 기능 구현"
  com.nuttty.eureka.auth/build.gradle
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/dto/UserInfoDto.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/service/AuthService.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/domain/model/User.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/domain/model/UserRoleEnum.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/domain/repository/UserRepository.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/infrastructure/configuration/JpaConfig.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/infrastructure/configuration/SecurityConfig.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/presentation/controller/AuthController.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/presentation/request/SignupRequestDto.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/util/AuditEntity.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/util/AuditorAwareImpl.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/util/ResultResponse.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/util/SuccessCode.java
Labels: enhancement

#38 [#34] Feat: "회원 상세 조회 기능 구현"
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/service/UserService.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/presentation/controller/UserController.java
Labels: enhancement

#31 [#5] 허브 생성, 수정, 삭제
  com.nuttty.eureka.hub/build.gradle
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/HubApplication.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/application/client/UserClient.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/application/dto/ErrorResponse.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/application/dto/HubDto.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/application/dto/UserDto.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/application/service/HubService.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/aspect/LoggingAspectOfHub.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/domain/model/Hub.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/exception/GlobalExceptionHandler.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/infrastructure/repository/HubRepository.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/presestation/controller/HubController.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/presestation/request/HubRequest.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/presestation/response/HubDelResponse.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/presestation/response/HubResponse.java
  com.nuttty.eureka.hub/src/main/resources/application.yml
  com.nuttty.eureka.hub/src/main/resources/schema.sql
Labels: enhancement

#39 [#6] 허브 페이징 전체 조회 및 개별 조회
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/HubApplication.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/application/dto/HubDto.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/application/service/HubService.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/domain/model/Hub.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/domain/repository/HubRepositoryCustom.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/infrastructure/repository/HubRepository.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/infrastructure/repository/HubRepositoryImpl.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/presestation/controller/HubController.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/presestation/request/HubRequestDto.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/presestation/request/HubSearchRequestDto.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/presestation/response/HubDelResponseDto.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/presestation/response/HubResponseDto.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/presestation/response/HubSearchResponseDto.java
Labels: enhancement

#40 [#6] 조회 정렬 조건 및 defalut 페이지 사이즈 변경
  com.nuttty.eureka.hub/build.gradle
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/infrastructure/repository/HubRepositoryImpl.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/presestation/controller/HubController.java
Labels: refactor

#41 [#16] 허브 정보 캐싱
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/application/dto/HubDto.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/application/service/HubService.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/config/CacheConfig.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/presestation/response/HubResponseDto.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/presestation/response/HubSearchResponseDto.java
Labels: enhancement

#42 [#13] DB 초기화 및 더미 데이터 생성
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/domain/model/Hub.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/domain/model/HubRoutes.java
  com.nuttty.eureka.hub/src/main/resources/application.yml
  com.nuttty.eureka.hub/src/main/resources/schema.sql
Labels: refactor

#43 [#8] 업체 생성, 수정, 삭제
  com.nuttty.eureka.company/build.gradle
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/CompanyApplication.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/application/client/AuthClient.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/application/client/HubClient.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/application/dto/AuthDto.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/application/dto/AuthRequestDto.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/application/dto/CompanyDto.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/application/dto/ErrorResponse.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/application/dto/HubDto.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/application/dto/HubRequestDto.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/application/service/CompanyService.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/aspect/LoggingAspectOfHub.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/domain/model/Company.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/exception/GlobalExceptionHandler.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/exception/exceptionsdefined/DelegationException.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/infastructure/repository/CompanyRepository.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/presentation/controller/CompanyController.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/presentation/request/CompanyRequestDto.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/presentation/response/CompanyDelResponseDto.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/presentation/response/CompanyResponseDto.java
  com.nuttty.eureka.company/src/main/resources/application.yml
  com.nuttty.eureka.company/src/main/resources/schema.sql
Labels: enhancement

#44 [#6] Auth Client 코드 수정 및 글로벌 예외 추가
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/application/client/UserClient.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/application/dto/AuthDto.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/application/dto/AuthRequestDto.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/application/service/HubService.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/exception/GlobalExceptionHandler.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/exception/exceptionsdefined/DelegationException.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/presestation/controller/HubController.java
Labels: refactor

#45 [#9] 업체 개별, 페이지 조회 구현
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/application/dto/CompanyDto.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/application/service/CompanyService.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/domain/repository/CompanyRepositoryCustom.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/infastructure/repository/CompanyRepository.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/infastructure/repository/CompanyRepositoryImpl.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/presentation/controller/CompanyController.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/presentation/request/CompanySearchRequestDto.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/presentation/response/CompanySearchResponseDto.java
Labels: enhancement

#51 [#5] Auth Client 설정 및 코드 수정, 더미 데이터 및 swagger 설정
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/AuthApplication.java
  com.nuttty.eureka.auth/src/main/resources/application.yml
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/HubApplication.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/application/client/UserClient.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/application/dto/AuthDto.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/application/dto/AuthRequestDto.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/application/service/HubService.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/config/AuditorAwareImpl.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/config/SwaggerConfig.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/presestation/controller/HubController.java
  com.nuttty.eureka.hub/src/main/resources/schema.sql
Labels: refactor

#52 [#20] 주문 생성
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/OrderApplication.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/fegin/CompanyClient.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/fegin/ProductClient.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/fegin/dto/CompanyDataDto.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/fegin/dto/CompanyInfoDto.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/fegin/dto/ProductDataDto.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/fegin/dto/ProductInfoDto.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/service/OrderService.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/model/AuditEntity.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/model/Delivery.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/model/DeliveryRoute.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/model/DeliveryStatus.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/model/HubRoute.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/model/Order.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/model/OrderProduct.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/repository/OrderRepository.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/service/OrderDomainService.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/infrastructure/repository/JpaOrderRepository.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/presentation/controller/OrderController.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/presentation/dto/OrderProductDto.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/presentation/dto/OrederDto.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/presentation/dto/ResultResponse.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/util/SuccessCode.java
Labels: enhancement

#54 [#37] Feat: "회원 탈퇴 구현"
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/service/UserService.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/presentation/controller/UserController.java
  com.nuttty.eureka.auth/src/main/resources/application.yml
Labels: enhancement

#55 [#9] Client 예외 처리 및 by-email 변경
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/application/client/AuthClient.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/application/dto/AuthRequestDto.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/application/service/CompanyService.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/config/AuditorAwareImpl.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/domain/model/CompanyType.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/exception/GlobalExceptionHandler.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/exception/exceptionsdefined/MissmatchException.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/presentation/controller/CompanyController.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/presentation/request/CompanyRequestDto.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/application/client/AuthClient.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/application/service/HubService.java
Labels: refactor

#57 [#35] Feat: "회원 검색 구현"
  com.nuttty.eureka.auth/build.gradle
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/AuthApplication.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/dto/UserInfoDto.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/dto/UserSearchResponseDto.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/service/AuthService.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/service/UserService.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/domain/repository/JpaUserRepository.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/infrastructure/repository/UserRepository.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/infrastructure/repository/UserRepositoryImpl.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/presentation/controller/UserController.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/presentation/request/UserSearchRequestDto.java
Labels: enhancement

#58 [#12] 상품 페이징 전체 조회 및 개별 조회
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/application/dto/ProductDto.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/application/service/ProductService.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/domain/model/Product.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/domain/repository/ProductRepositoryCustom.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/infastructure/repository/CompanyRepository.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/infastructure/repository/ProductRepository.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/infastructure/repository/ProductRepositoryImpl.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/presentation/controller/CompanyController.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/presentation/controller/ProductController.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/presentation/request/ProductRequestDto.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/presentation/request/ProductSearchRequestDto.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/presentation/response/ProductSearchResponseDto.java
  com.nuttty.eureka.company/src/main/resources/schema.sql
Labels: enhancement, refactor

#64 [#59] Feat: "회원 관련 캐싱 기능 구현"
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/dto/UserSearchResponseDto.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/service/UserService.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/infrastructure/configuration/CacheConfig.java
Labels: enhancement

#68 [#60] Refactor: "Auth - Verify 메소드 캐싱"
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/service/AuthService.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/service/UserService.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/infrastructure/configuration/CacheConfig.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/presentation/controller/AuthController.java
Labels: refactor

#69 [#56] Feat: "배송 경로 기록 생성"
  com.nuttty.eureka.order/build.gradle
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/fegin/CompanyClient.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/fegin/HubClient.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/fegin/ProductClient.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/fegin/dto/CompanyDataDto.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/fegin/dto/CompanyInfoDto.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/fegin/dto/ContentDto.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/fegin/dto/HubDto.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/fegin/dto/HubResponse.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/fegin/dto/ProductDto.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/fegin/dto/ProductInfoDto.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/service/HubRouteInitializer.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/service/HubRouteService.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/service/OrderService.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/model/Delivery.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/model/DeliveryRoute.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/model/HubRoute.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/model/Order.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/model/OrderProduct.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/service/OrderDomainService.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/infrastructure/repository/HubRouteRepository.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/presentation/dto/OrderProductDto.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/presentation/dto/OrederDto.java
Labels: enhancement

#71 [#67] Feat: "배송 담당자 등록 구현"
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/client/HubClient.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/dto/DeliveryPersonInfoDto.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/dto/HubDto.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/service/DeliveryPersonService.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/domain/model/DeliveryPerson.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/domain/model/DeliveryPersonTypeEnum.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/domain/repository/DeliveryPersonRepositoryCustom.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/domain/repository/UserRepositoryCustom.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/exception/GlobalExceptionHandler.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/exception/custom/DeliveryPersonAlreadyExistsException.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/infrastructure/repository/DeliveryPersonRepository.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/infrastructure/repository/UserRepository.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/infrastructure/repository/UserRepositoryImpl.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/presentation/controller/DeliveryPersonController.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/presentation/controller/UserController.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/presentation/request/DeliveryPersonCreateDto.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/presentation/request/HubRequestDto.java
Labels: enhancement

#76 [#72] Feat: "배송 담당자 개별 조회 기능 구현 & 등록 기능 권한 별 검사 로직 추가"
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/service/DeliveryPersonService.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/domain/model/DeliveryPerson.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/presentation/controller/DeliveryPersonController.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/presentation/request/DeliveryPersonCreateDto.java
Labels: enhancement, refactor

#77 [#73] Feat: "배송 담당자 타입 수정 기능 구현 & 배송 담당자 타입별 검사 로직 수정"
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/service/DeliveryPersonService.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/service/UserService.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/domain/model/DeliveryPerson.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/presentation/controller/DeliveryPersonController.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/presentation/request/DeliveryPersonTypeUpdateRequestDto.java
Labels: enhancement, refactor

#79 [#70] Feat: "주문 조회 구현"
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/service/OrderService.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/config/JpaConfig.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/config/UserAuditorAware.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/model/Delivery.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/model/DeliveryRoute.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/model/HubRoute.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/model/Order.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/model/OrderStatus.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/repository/OrderRepository.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/repository/OrderRepositoryCustom.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/service/OrderDomainService.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/infrastructure/repository/JpaOrderRepository.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/infrastructure/repository/OrderRepository.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/infrastructure/repository/OrderRepositoryImpl.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/presentation/controller/OrderController.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/presentation/dto/OrederDto.java
Labels: enhancement

#80 Feature/63 ai wheather
  .gitignore
  com.nuttty.eureka.ai/.gitignore
  com.nuttty.eureka.ai/build.gradle
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/AiApplication.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/client/CompanyClient.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/client/DeliveryPersonClient.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/client/OrderClient.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/dto/ErrorResponse.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/dto/ai/AiDto.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/dto/ai/AiSearchRequestDto.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/dto/company/CompanyDto.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/dto/delivery/DeliveryDto.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/dto/delivery/DeliveryRequestDto.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/dto/delivery/DeliveryRouteDto.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/dto/deliveryperson/DeliveryPersonDto.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/dto/deliveryperson/DeliveryPersonRequestDto.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/dto/order/DeliveryDto.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/dto/order/OrderDto.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/dto/order/OrderItemDto.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/dto/order/OrderReceiverDto.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/dto/order/OrderRequestDto.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/dto/order/OrderSupplierDto.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/dto/slackmessage/SlackMessageDto.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/service/AiService.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/aspect/LoggingAspectOfAi.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/config/AuditorAwareImpl.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/config/JsonFormatter.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/config/RestTemplateConfig.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/domain/model/Ai.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/domain/model/AuditEntity.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/domain/repository/AiRepositoryCustom.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/domain/service/DeliveryPersonService.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/domain/service/GeminiApiService.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/domain/service/HubMappingOrderService.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/domain/service/SlackService.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/exception/GlobalExceptionHandler.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/exception/exceptionsdefined/ClientException.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/infrastructure/repository/AiRepository.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/infrastructure/repository/AiRepositoryImpl.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/presentation/controller/AiController.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/presentation/response/AiResponseDto.java
  com.nuttty.eureka.ai/src/main/resources/application.yml
  com.nuttty.eureka.ai/src/main/resources/schema.sql
  com.nuttty.eureka.auth/src/main/resources/application.yml
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/application/dto/SupplierDto.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/application/service/CompanyService.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/infastructure/repository/CompanyRepository.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/presentation/controller/CompanyController.java
  com.nuttty.eureka.company/src/main/resources/application.yml
  com.nuttty.eureka.gateway/src/main/resources/application.yml
  com.nuttty.eureka.hub/src/main/resources/application.yml
  com.nuttty.eureka.hub/src/main/resources/schema.sql
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/presentation/dto/OrederDto.java
  com.nuttty.eureka.order/src/main/resources/application.yml
Labels: enhancement

#82 [#75] Feat: "배송 담당자 전체 조회 기능 구현"
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/dto/DeliveryPersonSearchResponseDto.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/service/DeliveryPersonService.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/service/UserService.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/domain/repository/DeliveryPersonRepositoryCustom.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/infrastructure/repository/DeliveryPersonRepositoryImpl.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/presentation/controller/DeliveryPersonController.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/presentation/request/DeliveryPersonSearchRequestDto.java
Labels: enhancement

#83 [#63] 환경변수 삭제 및 Gemini 예외 처리
  .gitignore
  com.nuttty.eureka.ai/.gitignore
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/service/AiService.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/domain/service/GeminiApiService.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/domain/service/HubMappingOrderService.java
Labels: refactor

#85 [#81] Feat: "주문 소프트 삭제 및 주문 상태 변경"
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/service/OrderService.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/model/Order.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/service/OrderDomainService.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/presentation/controller/OrderController.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/presentation/dto/OrederDto.java
Labels: enhancement

#88 [#8]: 업체 생성, 수정 시 허브 관리자 로직 수정
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/application/service/CompanyService.java
Labels: refactor

#89 [#84] 허브 별 주문 정보 배송 담당자 코드 수정
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/client/DeliveryPersonClient.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/client/OrderClient.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/dto/deliveryperson/DeliveryPersonDto.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/dto/deliveryperson/DeliveryPersonSearchDto.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/dto/slackmessage/SlackRequestDto.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/service/AiService.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/domain/service/DeliveryPersonService.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/domain/service/GeminiApiService.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/domain/service/HubMappingOrderService.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/domain/service/SlackService.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/domain/service/WeatherService.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/domain/model/DeliveryPersonTypeEnum.java
Labels: refactor

#90 [#86] Feat: "배송 경로 조회 및 배송 단건 조회"
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/service/DeliveryRouteService.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/service/DeliveryService.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/model/Delivery.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/model/DeliveryRoute.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/infrastructure/repository/OrderRepository.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/presentation/controller/DeliveryController.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/presentation/controller/DeliveryRouteController.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/presentation/dto/DeliveryDto.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/presentation/dto/DeliveryRouteDto.java
Labels: enhancement

#92 [#91] Feat: "배송 검색 페이징 조회"
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/service/DeliveryService.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/repository/OrderRepositoryCustom.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/infrastructure/repository/OrderRepositoryImpl.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/presentation/controller/DeliveryController.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/presentation/dto/DeliveryDto.java
Labels: enhancement

#93 [#91] Feat: "배송 상태 수정"
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/service/DeliveryService.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/model/Delivery.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/presentation/controller/DeliveryController.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/presentation/dto/DeliveryDto.java
Labels: enhancement

#101 [#94] 주문 도메인 전역 예외 처리
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/service/DeliveryRouteService.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/service/DeliveryService.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/service/OrderService.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/config/FeginConfig.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/service/OrderDomainService.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/exception/FeginErrorDecoder.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/exception/GlobalExceptionHandler.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/exception/exceptionsdefined/ExternalServiceException.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/exception/exceptionsdefined/InsufficientStockException.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/exception/exceptionsdefined/OrderNotFoundException.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/presentation/dto/ErrorResponse.java
Labels: enhancement, refactor

#103 [#87] Refactor: "Spring Security & Jwt 기반 인증,인가 방식으로 개선"
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/dto/TokenDto.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/jwt/CustomPreAuthFilter.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/jwt/JwtUtil.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/security/UserDetailsImpl.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/security/UserDetailsServiceImpl.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/service/AuthService.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/service/DeliveryPersonService.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/application/service/UserService.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/exception/GlobalExceptionHandler.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/exception/custom/AlreadyIsDeletedException.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/infrastructure/configuration/SecurityConfig.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/presentation/controller/AuthController.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/presentation/controller/DeliveryPersonController.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/presentation/controller/UserController.java
  com.nuttty.eureka.gateway/build.gradle
  com.nuttty.eureka.gateway/src/main/java/com/nuttty/eureka/gateway/application/dto/CustomHeaderDto.java
  com.nuttty.eureka.gateway/src/main/java/com/nuttty/eureka/gateway/application/jwt/JwtUtil.java
  com.nuttty.eureka.gateway/src/main/java/com/nuttty/eureka/gateway/application/service/AuthService.java
  com.nuttty.eureka.gateway/src/main/java/com/nuttty/eureka/gateway/configuration/SecurityConfig.java
  com.nuttty.eureka.gateway/src/main/java/com/nuttty/eureka/gateway/filter/LocalJwtAuthenticationFilter.java
  com.nuttty.eureka.gateway/src/main/java/com/nuttty/eureka/gateway/infrastructure/AuthClient.java
Labels: refactor

#104 [#98] config 설정 및 게이트웨이 방화벽 설정
  com.nuttty.eureka.ai/build.gradle
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/dto/order/OrderDto.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/config/SecurityConfig.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/domain/service/SlackService.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/presentation/controller/AiController.java
  com.nuttty.eureka.ai/src/main/resources/application.yml
  com.nuttty.eureka.company/build.gradle
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/config/SecurityConfig.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/presentation/controller/CompanyController.java
  com.nuttty.eureka.company/src/main/resources/application.yml
  com.nuttty.eureka.config/src/main/resources/application.yml
  com.nuttty.eureka.config/src/main/resources/config-repo/ai-service-local.yml
  com.nuttty.eureka.config/src/main/resources/config-repo/company-service-local.yml
  com.nuttty.eureka.config/src/main/resources/config-repo/hub-service-local.yml
  com.nuttty.eureka.gateway/src/main/java/com/nuttty/eureka/gateway/configuration/RestTemplateConfig.java
  com.nuttty.eureka.gateway/src/main/java/com/nuttty/eureka/gateway/presentation/controller/ActuatorRefreshController.java
  com.nuttty.eureka.gateway/src/main/resources/application.yml
  com.nuttty.eureka.hub/build.gradle
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/config/SecurityConfig.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/presestation/controller/HubController.java
  com.nuttty.eureka.hub/src/main/resources/application.yml
Labels: enhancement

#105 [#98] config 설정 및 게이트웨이 방화벽 설정
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/config/SecurityConfig.java
Labels: bug, refactor

#106 [#98] config 설정 및 게이트웨이 방화벽 설정
  com.nuttty.eureka.gateway/src/main/java/com/nuttty/eureka/gateway/presentation/controller/ActuatorRefreshController.java
Labels: bug

#109 [#98] 시큐리티 스웨거 포트, url 설정
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/config/SecurityConfig.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/config/SecurityConfig.java
  com.nuttty.eureka.gateway/src/main/java/com/nuttty/eureka/gateway/configuration/SecurityConfig.java
  com.nuttty.eureka.gateway/src/main/resources/application.yml
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/config/SecurityConfig.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/config/SecurityConfig.java
Labels: refactor

#110 [#98] Client 호출 파라미터 포트 추가, Actuator 설정 코드 config 설정으로 변경
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/client/CompanyClient.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/client/HubClient.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/client/OrderClient.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/domain/service/DeliveryService.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/domain/service/HubMappingOrderService.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/domain/service/HubService.java
  com.nuttty.eureka.ai/src/main/resources/application.yml
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/application/client/HubClient.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/application/service/CompanyService.java
  com.nuttty.eureka.company/src/main/resources/application.yml
  com.nuttty.eureka.config/src/main/resources/config-repo/ai-service-local.yml
  com.nuttty.eureka.config/src/main/resources/config-repo/company-service-local.yml
  com.nuttty.eureka.config/src/main/resources/config-repo/hub-service-local.yml
  com.nuttty.eureka.config/src/main/resources/config-repo/order-service-local.yml
  com.nuttty.eureka.hub/src/main/resources/application.yml
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/fegin/CompanyClient.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/service/OrderService.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/infrastructure/repository/OrderRepositoryImpl.java
  com.nuttty.eureka.order/src/main/resources/application.yml
Labels: refactor

#111 [#98] config - 집킨 설정 코드 추가
  com.nuttty.eureka.config/src/main/resources/config-repo/ai-service-local.yml
  com.nuttty.eureka.config/src/main/resources/config-repo/company-service-local.yml
  com.nuttty.eureka.config/src/main/resources/config-repo/hub-service-local.yml
  com.nuttty.eureka.config/src/main/resources/config-repo/order-service-local.yml
Labels: documentation

#113 Naver Direction5 API 연동 및 캐싱 적용, resilience4j 재시도 실패시 트랜잭션 롤백
  com.nuttty.eureka.config/src/main/resources/config-repo/order-service-local.yml
  com.nuttty.eureka.order/build.gradle
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/fegin/AuthClient.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/fegin/dto/DirectionsResponse.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/fegin/dto/HubDto.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/fegin/dto/UserDto.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/fegin/dto/UserRoleEnum.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/fegin/dto/WayPoint.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/jwt/CustomPreAuthFilter.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/jwt/JwtUtil.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/security/UserDetailsImpl.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/security/UserDetailsServiceImpl.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/service/DeliveryRouteService.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/service/HubRouteInitializer.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/service/HubRouteService.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/application/service/NaverDirectionService.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/config/CacheConfig.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/config/RestTmplateConfig.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/config/SecurityConfig.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/domain/model/HubRoute.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/presentation/controller/DeliveryController.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/presentation/controller/DeliveryRouteController.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/presentation/controller/OrderController.java
Labels: enhancement, refactor

#115 Docs: "Auth 서비스 Swagger 문서화 작업"
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/presentation/controller/AuthController.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/presentation/controller/DeliveryPersonController.java
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/presentation/controller/UserController.java
Labels: documentation

#116 order swagger 문서 작업
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/presentation/controller/DeliveryController.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/presentation/controller/DeliveryRouteController.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/presentation/controller/OrderController.java
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/presentation/dto/OrederDto.java
Labels: documentation

#117 Docs: Hub, Company, Ai, Product Swagger 문서화 작업
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/config/SecurityConfig.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/presentation/controller/AiController.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/config/SecurityConfig.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/presentation/controller/CompanyController.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/presentation/controller/ProductController.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/presentation/request/CompanyRequestDto.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/presentation/request/ProductRequestDto.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/presentation/request/ProductUpdateRequestDto.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/config/SecurityConfig.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/presestation/controller/HubController.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/presestation/request/HubRequestDto.java
  com.nuttty.eureka.order/build.gradle
  com.nuttty.eureka.order/src/main/java/com/nuttty/eureka/order/config/SecurityConfig.java
Labels: documentation

#118 Docs: "API 스크립트 테스트 파일 추가"
  api_script_test.http
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/application/service/CompanyService.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/domain/model/Company.java
Labels: documentation

#120 [#96 ] 허브 nx,ny 격자 좌표 추가
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/application/dto/hub/HubDto.java
  com.nuttty.eureka.ai/src/main/java/com/nuttty/eureka/ai/domain/service/WeatherService.java
  com.nuttty.eureka.company/src/main/java/com/nuttty/eureka/company/application/dto/HubDto.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/application/dto/HubDto.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/domain/model/Hub.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/infrastructure/repository/HubRepositoryImpl.java
  com.nuttty.eureka.hub/src/main/java/com/nuttty/eureka/hub/presestation/request/HubRequestDto.java
Labels: refactor

#121 Refactor: "Auth 서비스 추가 개선"
  README.md
  com.nuttty.eureka.auth/build.gradle
  com.nuttty.eureka.auth/src/main/java/com/nuttty/eureka/auth/infrastructure/configuration/SecurityConfig.java
  com.nuttty.eureka.auth/src/main/resources/application.yml
  com.nuttty.eureka.config/src/main/resources/config-repo/auth-service-local.yml
Labels: refactor
